### PR TITLE
Hotfix/svgo issues

### PR DESCRIPTION
**Pull request by coreymcollins**
### DESCRIPTION

@itsamoreh ran into this issue and fixed it on a project. This is me jumping in here to add his fix to wd_s!

The issue was that something with ImageMin running on SVGs/the SVG sprite was causing a bizarre issue where _sometimes_ SVG sprites wouldn't generate. It felt kind of hit or miss when Amor and I chatted yesterday.

Nevertheless, this removes SVGs from ImageMin completely. The SVG SpriteMap plugin (apparently) minifies on its own without an extra step/plugin being needed.

### OTHER

- [x] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [x] Does this pass CBT?

### STEPS TO VERIFY

1. Check out the branch
2. Run `npm run build`
3. Run `npm run watch` and add some SVG files

You should see no real change in how this should have always worked – the SVG sprite should be generated and any new SVG files added to the `/build/images/icons/` directory.

### DOCUMENTATION

No updates needed here.

### CODE REVIEW

**Review by itsamoreh — APPROVED** [review]
This works great!

I tested by removing the `<defs>` in `close.svg` which was breaking the sprite before and also tested by dropping in an entirely new set of icons and everything is good in both situations.

**Review by gregrickaby — CHANGES_REQUESTED** [review]
@coreymcollins If we're not using `image-webpack-plugin` can you also remove it as a dev dependency in `package.json`?

**Comment by coreymcollins** [comment]
> @coreymcollins If we're not using `image-webpack-plugin` can you also remove it as a dev dependency in `package.json`?

We're still using it in our `webpack.prod.js` file to minify other images, we're just not using it in `webpack.config.js` or minifying SVG files with it in our `prod` file anymore.

**Review by gregrickaby — APPROVED** [review]
@coreymcollins Gotcha. Approved!

**Pull request merged**
