### PR TITLE
Feature/gulp plus webpack

### LINKED ISSUE #389: Webpack
Because of the time suck that was #341, I'd like to try and make the switch to Webpack. 
I'm throwing this out as an example, since I've already put a ton of time into this Webpack config (modeling it after wd_s Gulp workflow): https://github.com/gregrickaby/MoaningMyrtle. 

**Couple things**

- Our current Gulp workflow to be the model we work towards! Meaning, I'd like our Webpack workflow to be as close to a 1:1 match as possible.

- I'd also like to keep Gulp in a feature branch for several months, to give folks time to transition. We did the same thing when we moved from Grunt --> Gulp.

**Other considerations**

- Drop sass-lint for [stylelint](https://stylelint.io/)
- Update to Babel 7
- Drop Sass Docs
- I want linting to happen with each compile (see my example Webpack config, it does this)
- BrowserSync stays!
- NPM scripts all they way
- Move browerlist to `package.json` 
- Update our linting configs to match WDS Code Standards

### PR DESCRIPTION
**Pull request by efuller**
Closes #389 

### DESCRIPTION ###
I know that there is another PR out there for this issue and it consists of a webpack only solution. Haris had initially asked me to look into an issue with CSS images and relative URLs. After a lot of research and testing, I came to the conclusion that we could make things work, but we would need to change how we use images within our CSS/Sass. 

While I was researching and testing the relative URL issue, I was also noticing that the performance was not great when using just webpack.  Builds seemed slower than what we've been used to and _watch_ mode wasn't as fast as I would expect.

At this point, I decided to look into the idea of keeping Gulp intact and configuring it to use webpack for transpiling and bundling the JavaScript.

While researching this, I found a great article on CSS tricks that I used as a guide. Find it here: https://css-tricks.com/combine-webpack-gulp-4/

### What's Changed
- Browser sync is still being used but in conjunction with `hot-reloading` from webpack. *Most of the time*, this allows for CSS and JS to be injected into the page without a page reload. If the injection fails, the page should reload as a fallback. There may be occasions where you need to manually refresh the page.
- We should be able to freely write ES6 and it should be transpiled down to ES5. By default, I've set it to transpile for the `last 2 versions`. If we need IE11 support, please see this commit: 16ffcdb9562acb4a4bc10fd11f7b44c20c7bd524
- The babel-loader is set up to watch `.jsx` files as well! We can write React JSX if we'd like :)
- jQuery has been added in as an external. It should just be available in our code like it always has been.
- I took the liberty to refactor the `Gulpfile.js` file. I've broken it out into smaller modules inside the `tasks` folder. This an opinionated change but definitely open for discussion!
- Although running `gulp the-task` will still work, `npm start scripts` have been set up and should be used instead of running Gulp directly. Using `npm` allows us to easily specify environment variables.
- I have created a `tasks/theme-config.js` file that is used as a single source of truth for the overall tooling configuration. Change things in this file such as the theme name and local dev URL.

### Usage
1. Run `npm install` like you normally would.
2. Go into `tasks/theme-config.js` and set the `localURL`, `themeName`, and `watchURL`.

### Scripts
- `npm run build` - Build all the things in production mode.
- `npm run build:js` - Build JS in production mode.
- `npm run dev` - Compile all the things in development mode.
- `npm run dev:js` - Compile JS files in development mode.
- `npm run dev:styles` - Compile styles.
- `npm run eslint` - Run eslint.
- `npm run eslint:fix` - Run ESlint and fix all the things.
- `npm run watch` - Will watch and inject changes.

### NEEDS TESTING
Would love to put `npm run watch` through some testing to see just how well it operates.

### Important Note
For a good while now, slow changes when watching files seems to have been a thing for those of us using Local by Flywheel. Although this fix can be buggy, I'd recommend going into Preferences -> Advanced and turning onthe IPv6 Loopback. I don't know what this does exactly, but it seems to speed up Browser sync usage.

They make a note of it, but if this is turned on and you try to access a site and all that's displayed is a `It Works!` message, then just turn the IPv6 back off.

### SCREENSHOTS ###
Here is a link to a video showing browser sync plus hot module reloading: https://d.pr/v/yD6Bec

### OTHER ###
- [ ] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [X] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [ ] Does this pass CBT?

### DOCUMENTATION ###
Once we work out the bugs and finalize all the things, I will update the documentation.

### FUTURE TODOS
- Remove the usage of Bower
- Now that we have the ability, we need to formulate a new way to write our JS so that we can utilize moduels.

### CODE REVIEW

**Review by gregrickaby — CHANGES_REQUESTED** [review]
@efuller Amazing work here. I'm very excited about all these changes and the things you've done in this PR. I followed your setup instructions and then ran `npm run watch`, and went to https://localhost:3000

1. Changing Sass resulted in a successful hot reload ✔️ 
2. I deliberately broke a jQuery component, which resulted in a hot reload, but the component still worked, when it should not have. 🤷‍♂️ 
3. When I changed a PHP file, it broke `npm run watch` altogether. 🙃 

If you'd like, we can screen share and go over these two errors. Lemme know!

**Comment by coreymcollins** [comment]
I'm having a different, but still buggy, experience from Greg.

1. Changing Sass resulted in a successful hot reload ✔️ 
2. Changing a JS file, regardless if I made a breaking change or not, never caused a hot reload. I changed the class name of the `scripts/src/components/carousel.js` file on line `24` and nothing happened. I reloaded manually and the carousel stopped working, as expected. I changed it back then changed a setting in the carousel initialization to change slides at 400ms instead of 5000ms and, again, didn't see a change until I manually reloaded. Actually breaking something by causing a syntax error stopped `watch` but results in no change in the browser.
3. I was able to make a change in a `php` file with no issues. I added some text to the `404.php` file and the browser reloaded the change immediately. ✔️ 

Edit: I see another commit snuck in here which apparently resolves the `php` file issue, so that's probably why it's working for me now!

**Comment by efuller** [comment]
@gregrickaby @coreymcollins 
Thanks for the feedback!

As much as I wanted it, having HMR in place for JS will be too inconsistent in terms of reliability. Some but not all changes will be injected. From what I can gather, this is because our code depends on `jQuery.ready()` which isn't triggered on injection as well as JS events won't be removed properly because there is no page load.

The fix consists of manually telling browser sync to reload on changes. This looks to end up working out nicely because CSS changes are still injected while any JS changes will prompt a page to reload.

I also snuck in a quick fix for reloading when a `.php` file changes!

## Sass/Css


## JS

**Comment by coreymcollins** [comment]
Can confirm editing PHP, JS, and SCSS files all now reload the page. SCSS files get an instant refresh while PHP and JS reload as if you've hit the reload button in your browser.

Going to do some more testing with the other scripts but so far `npm run watch` seems to be working great!

**Review by gregrickaby — APPROVED** [review]

**Comment by gregrickaby** [comment]
Also confirmed the issues from yesterday are now working. Thanks @efuller!! 🌮

**Review by coreymcollins — CHANGES_REQUESTED** [review]
So far everything is working smoothly. I chatted with Eric briefly and threw around some potential ideas to beef this up a bit:
- Add `npm run sasslint` and `npm run sasslint:fix` to check and fix our Sass files
- Add `npm run phpcs` and `npm run phpcs:fix` to check and fix our PHP files
- Add listeners to `npm run watch` to alert the user when they write bad JS, Sass, or PHP

Some things that may be missing or need updating:
- There doesn't seem to be anything listening to the `/sprites/` directory. With `npm run watch` running, nothing happens when I add an image to the folder. Running `npm run build` does not create a `sprites.png` image. Conversely, the `/svg-icons/` functionality seems to be working as expected.
- There are various `README.md` files in the theme, like in the `/sprites/` directory, which will need to be updated to reflect the new `npm xxx` functions

I'm going to keep kicking the wheels, but wanted to at least get these noted as I keep on keeping on.

Thanks for the great work here!

**Comment by efuller** [comment]
A few more updates today. I think we are close!

Recap:
- Added `npm` scripts for all the things. These are now documented in the readme.
- Removed `spritesmith` usage. This seems to be feature that is almost never used.
- Setup `eslint` and `sass-lint` to run on watch. I was originally going to have webpack lint the JS, but it was breaking browsersync so I set it up to work with gulp.
- Setup `phpcs` This seems to work well, and it runs against our coding standards by default.
- Attempted to setup `phpcbf` (auto fix phpcs errors), but was not getting desired results. The `gulp-phpcbf` plugin hasn't been updated in 4 years.
- Updated the main readme file.

I think this is ready for another round of testing!

**Comment by coreymcollins** [comment]
Eric, this rules! I broke some Sass and PHP and ran the various functions you setup, both of which found my errors. I really love the ease of having everything built into one spot and for everybody to be able to check this stuff in a snap.

One thing I've noticed is that ES Lint doesn't seem to be listening to the files in the `/assets/scripts/` top-level directory. This makes sense, in general, because that's where our compiled `project.js` file goes – but we also have Customizer and Scaffolding JS files in there which don't throw errors if I break something with `npm run watch` running.

I wonder if it'd be best to move those JS files out of the root folder and into a subdirectory? We'd need to update our enqueues for the new location, but I don't think we'd want to or be able to have the `.js` and `.min.js` files separated the same way we're doing with our compiled components as, depending on the server, we'll either be looking to enqueue the minified or non-minified version.

Let me know what you think, and thanks again for the awesome work here!

**Comment by efuller** [comment]
@coreymcollins 
I made some additional adjustments here!

- I added a `customizer` and `scaffolding` folder to the `scripts` folder. These will house the scripts you would edit for dev.
- I then added entry points for each in gulp and webpack. Nothing should change in terms of how they are compiled. They will still compile to the `scripts` directory.
- The files should be *watched*.
- The files should also be linted on *watch* as well.

I think once the decisions around #461 are resolved and it is merged into this branch, there may be a few items to fix up, but this should be just about 💯 with these latest changes.

Feel free to pull down the changes and give them a spin!

**Pull request closed without merging**
