### PR TITLE
Wrap core blocks with wp-block-* classes

### PR DESCRIPTION
**Pull request by itsamoreh**
### DESCRIPTION

Some core blocks have these classes, some don't. This will wrap the core blocks we support that don't have these classes with wp-block-* classes.

### SCREENSHOTS

screen-capture 2022-10-07 at 10 18 33 AM

### STEPS TO VERIFY

Verify that the core blocks in the array have the block wrapper spans and the expected class names.

### CODE REVIEW

**Comment by jennahines** [comment]
@itsamoreh `core/freeform` returns `null` for `$block['blockName']` so it's not being wrapped. 
Screen Shot 2022-10-13 at 9 50 47 AM

**Comment by itsamoreh** [comment]
> @itsamoreh `core/freeform` returns `null` for `$block['blockName']` so it's not being wrapped.

Nice catch! Thanks Jenna.

Feels a bit gross but I'll add a case for `null` and wrap it with a `span.wp-block-freeform` unless someone has a better idea?

**Review by webdevstudios-hosting — CHANGES_REQUESTED** [review]
I'd like to see the other sass partials for adding containers to the other newly created classes. ie: `.wp-block-heading`, `.wp-block-list`, `.wp-block-html`

Thanks!

**Review by oliverharrison — APPROVED** [review]
Great!

**Review by oliverharrison — APPROVED** [review]
Great work.

**Review by oliverharrison — APPROVED** [review]

**Pull request merged**
