### PR TITLE
Hotfix/carousel bug

### PR DESCRIPTION
**Pull request by coreymcollins**
### DESCRIPTION ###
Made some adjustments to how the carousel works to fix a problem reported by @vadiom here: https://github.com/WebDevStudios/wd_s/commit/9dce9f0528bbf25a3ccadc31acfe6a13d1272c18#commitcomment-32536657

This update adds:
- Checks for the animation data attribute in `carousel.js` before trying to run animations
- Moves the animation classes from the parent carousel to the individual slides so they each animate on slide change
- Sets the content of the slides to `opacity: 0` on load, then transition to `opacity: 1` for smoother animations

This update fixes:
- Animates the individual slides, not the entire carousel so that slides animate on load
- Fixes up some JS which caused every carousel on the page to use the animation of the first carousel on the page

### OTHER ###
- [x] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [x] Does this pass CBT?

### STEPS TO VERIFY ###
Add a bunch of carousels with different animation options

### DOCUMENTATION ###
Will this pull request require updating the wd_s [wiki](https://github.com/WebDevStudios/wd_s/wiki)?

I don't believe so. This is all behind the scenes and _should_ just work without any extra steps.

### CODE REVIEW

**Comment by coreymcollins** [comment]
@jomurgel is doing some work in #474 that may refactor the carousel a bit, so I'm putting this one on hold for now and will lean on the updates in that PR to address the issues here.

Jo's plan is to move the font and animation options from the parent carousel to the individual slides, so each slide can have its own custom animation and font color set rather than a single animation and color set for the entire carousel. In doing that, the markup and JS will need to be refactored which should make the original issue reported here a moot point.

**Comment by jomurgel** [comment]
Some updates in #474 will address similar issues as this PR.

**Comment by coreymcollins** [comment]
This will be closed in #474, so just keeping this open until then to be doubly sure.

**Comment by coreymcollins** [comment]
Closed via #474.

**Pull request closed without merging**
