### PR TITLE
add word break for long entry-title, change padding to 6px on textarea, ...

### PR DESCRIPTION
**Pull request by stacyk**
...edit structure to use fill-parent instead of spanning 12 columns

### CODE REVIEW

**Comment by colorful-tones** [comment]
We might want to roll in a @mixin for word wrapping for wider support? See: Chris Coyier's "[Prevent Long URL’s From Breaking Out of Container](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/)"? e.g. 

```css
@mixin word-wrap() {
    word-break: break-word;
    -webkit-hyphens: auto;
    -moz-hyphens: auto;
    hyphens: auto;
} 
```

**Comment by gregrickaby** [comment]
Question... will Grunt's Auto Prefixer add MS support?

`ms-word-wrap: break-word;`

**Comment by colorful-tones** [comment]
AutoPrefixer just pulls from CanIUse.com database. Not sure we need `ms-word-wrap: break-word;` though.

**Comment by stacyk** [comment]
Turns out, this is not something autoprefixer will do.

But, I am getting it to work well without and prefix. According to the MS site, the prefix is only for IE8 (https://msdn.microsoft.com/en-us/library/ms531186(VS.85,loband).aspx), and Mozilla says not to use it: https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap

Do you prefer hyphens or breaking if there is an actual space:
http://sassmeister.com/gist/3f09e69a73e14859f967

**Pull request merged**
