### PR TITLE
Run [npm run theme] after successful webpack build so sprites and pot files are built.

### LINKED ISSUE #583: sprite.svg not generated during npm run start
When you first run `npm i`, the `sprite.svg` file will get created which is important for using the `display_svg` functions.

When you run `npm run start`, the `sprite.svg` file is cleared out and does not get recreated at any point. If you add or modify an SVG in the `src/images/icons` directory, that file will be added to/updated in the `build` directory, but the `sprite.svg` file is not generated.

We need to make sure the `sprite.svg` file is generated during `npm run start` so while actively developing so the sprite file is generated without having to stop the process and run `npm run build`.

### PR DESCRIPTION
**Pull request by aubreypwd**
This hooks into Webpack, and when a build is emitted, we run `npm run theme` so that pot files and sprites are re-generated into the build folder.

Closes https://github.com/WebDevStudios/wd_s/issues/583

### DESCRIPTION

image

This solves https://github.com/WebDevStudios/wd_s/issues/583 by ensuring that the WebPack build runs the commands we use to built the `sprite.svg` and `languages/*.pot` files. 

The issue in https://github.com/WebDevStudios/wd_s/issues/583 is that when you run `npm run theme` `theme:icons` is ran which generates the `build/images/icons/sprite.svg` file, but then on `npm run start` Webpack's `CopyWebpackPlugin` plugin essentially deletes `build/images` and copies `src/images/**` over. Ran in this order, the `build/images/icons/sprite.svg` file is deleted in the process and never generated again.

This solution fixes this by having Webpack run `npm run theme` after `CopyWebpackPlugin` plugin runs to re-generate the `build/images/icons/sprite.svg` file. 

It also fixes another underlying (and related issue) where the POT files in `build/languages/*.pot` are built once when `npm run them` runs on `postinstall` but are never regenerated again. Additionally this fix fixes that too since pot files are generated to the `build/languages/` folder on `npm run theme`. 

### STEPS TO VERIFY

Running `node@12` clone the directory and run `npm i` then run `npm run start` and e.g. modify an SVG in in `src/images/icon` and notice that unlike in https://github.com/WebDevStudios/wd_s/issues/583 the `build/images/sprite.svg` file is no longer deleted on `npm run start`.

## Will this pull request require updating the wd_s [wiki](https://github.com/WebDevStudios/wd_s/wiki)?

I don't think so.

### CODE REVIEW

**Comment by coreymcollins** [comment]
I think we'll need to find a more graceful solution to this. In my testing, saving a small change to a Sass partial is resulting in build times of 15+ seconds while running `npm run start`, compared to the current `main` branch which is around 4 seconds.

**Comment by coreymcollins** [comment]
We don't need to run the POT and SVG processes every time. Ideally, while running `npm run start` we'd be listening for changes to PHP files and SVG files and run those processes as needed, but right now *everything* runs whenever any change to any file is made.

**Comment by aubreypwd** [comment]
So it sounds like what you want to do is only run POT stuff when POT files change, and SVG stuff with SVG files change. I think we might be able to do that.

**Comment by coreymcollins** [comment]
Not sure if you've had a chance to look at #587, but I think we've solved the SVG issue there as part of some other add-ons/improvements.

**Pull request closed without merging**
