### PR TITLE
Experimental: esbuild

### PR DESCRIPTION
**Pull request by coreymcollins**
Experimental branch & PR to test esbuild in our flow.

So far, I have esbuild running to compile our CSS files (no more Sass) into a bundles build file. Currently hitting a wall with Tailwind, as Tailwind wants to compile to a massive 5.3mb file with no purging going on. Trying to get to the bottom of all of this.

Also added a separate script for imagemin & duplication, as the built-in handling from esbuild doesn't really match our flow/structure.

This work is ongoing and experimental, and (of course) open to collaboration!

### CODE REVIEW

**Comment by coreymcollins** [comment]
I pushed an update here to use a PR branch for imagemin based on a thread here: https://stackoverflow.com/a/62426873

The person in this PR: https://github.com/imagemin/imagemin/pull/353

Created a `preserveDirectories` flag to allow for you to use imagemin and retain the full directory structure, which imagemin doesn't do out of the box. It seems to do the job just fine, though I'm not sure if we'd want a more solid/supported solution if we end up going live with these updates at some point.

**Comment by coreymcollins** [comment]
With the latest updates this now:
- Compiles & minifies CSS
- Compiles Tailwind styles + purges unused Tailwind styles
- Compiles & minifies JS
- Optimizes images via imagemin
    - Using the experimental/PR branch noted above
- Optimizes SVGs via svgo + builds a sprite
- Compiles styles and scripts on `start` and `watch`

Will need to add a file watcher to run image scripts when files change in the `src` directories next.

**Comment by coreymcollins** [comment]
I pushed an update to watch images and update if something is changed, but it's not totally ideal. It WILL listen for images being added/removed and re-run image scripts, but it reruns processes on all of the images. Would be great to only run the imagemin stuff on the image(s) that changed. On this branch, images that are removed from `src` aren't also removed from `build`, which we do currently have on the `main` branch of wd_s.

**Comment by coreymcollins** [comment]
Just came across this package which seems to copy images, keeps the directory structure intact, and removes images from `build` if they were removed from `src`: https://www.npmjs.com/package/sync-directory

Going to do some more experimenting, but it looks promising so far.

**Comment by coreymcollins** [comment]
I think this may be ready for some more serious testing. Everything that we are currently doing in wd_s continues to work here in my testing (compiling, image copying & min, sprite map, linting and formatting) so I think it'd be good to do some stress testing and see if there are any additional packages we need/don't need or any other scripts we should be adding/removing/running in our processes.

I think we may still need to find a sourcemap solution.

**Comment by coreymcollins** [comment]
Just pushed an update that should bring sourcemaps back in!

**Comment by coreymcollins** [comment]
The following things need to be done:
- Going to need to manually resolve all of the conflicts we'll have here
- Will need to prep documentation for the updated processes and scripts once approved

Aside from those, I think this is ready for actual review so I'm going to un-draft this sucker.

**Comment by coreymcollins** [comment]
Updated this to include Critical CSS in the same way the `main` branch is now using it. Also a couple of housekeeping things with tidying up page templates and composer.

**Comment by coreymcollins** [comment]
I was working on an update which would allow for the separation of blocks into their own `/src/` and `/build/` directories. This utilizes an additional package ([esbuild-plugin-glob](https://github.com/waspeer/esbuild-plugin-glob)) to allow for the use of glob patterns in an esbuild `entryPoint`.

So, if we add blocks to our `/src/` directory like:
`/src/blocks/block-one/`
`/src/blocks/block-two/`

Inside of each block directory must live:
`block.css`: the block styles
`block.js`: the block scripts
`index.js`: the index file which imports both the CSS and JS file

The `index.js` file in each block directory will look like this:
```js
import './block.js';
import './block.css';
```

In our esbuild config file, our config gets updated like so:
```js
const postCssPlugin = require( 'esbuild-postcss' );
const { globPlugin } = require( 'esbuild-plugin-glob' );

const watch = process.argv.includes( '--watch' );

require( 'esbuild' )
	.build( {
		entryPoints: [
			'src/index.js',
			'src/critical.js',
			'./src/blocks/**/*/index.js',
		],
		bundle: true,
		outdir: 'build',
		preserveSymlinks: true,
		watch,
		logLevel: 'info',
		minify: true,
		external: [
			'*.svg',
			'*.png',
			'*.jpg',
			'*.jpeg',
			'*.gif',
			'*.woff',
			'*.woff2',
		],
		publicPath: 'build/images',
		plugins: [ postCssPlugin(), globPlugin() ],
		sourcemap: 'inline',
	} )
	.catch( () => process.exit( 1 ) );
```

The important lines are `entryPoints` and `plugins` to not only include the `globPlugin` we're requiring at the top of the file, but doing the important work of looking through our `src/blocks/` directory to find all `index.js` files.

When this builds, the blocks are built into individual directories in `/build/` like:
`/build/blocks/block-one/`
`/build/blocks/block-two/`

Each directory has its own `index.css` and `index.js` file with the styles and scripts specific to the block itself. No concatenation with other blocks or styles.

Here's a screenshot of the overall setup for an at-a-glance view:
screenshot of the esbuild.js configuration file

## HOWEVER ##
This additional plugin currently dies on `start`/`watch`. It kills the watch process for all files, so making updates to anything just goes out the window. It does work on `build`, which is nice.

There's a PR out on the `watch` issue from March that hasn't been merged in yet: https://github.com/waspeer/esbuild-plugin-glob/pull/10

I did try installing the package to that specific branch as suggested here: https://github.com/waspeer/esbuild-plugin-glob/issues/9#issuecomment-1062164098

This also didn't work to resolve the `watch` issue.

I haven't found another esbuild glob plugin yet, and esbuild doesn't let you use glob patterns for `entryPoints`.

Fingers crossed we can either find a replacement for that glob plugin or that fix gets merged in and things begin to work as expected!

**Comment by coreymcollins** [comment]
I was able to use the existing `glob` package we were using for our Tailwind config and updated the esbuild config to match:

```js
const postCssPlugin = require( 'esbuild-postcss' );
const glob = require( 'glob' );

const watch = process.argv.includes( '--watch' );

const blockDirs = glob.sync( './src/blocks/**/*/index.js' ),
	directoryFiles = [ './src/index.js', './src/critical.js' ];

require( 'esbuild' )
	.build( {
		entryPoints: blockDirs.concat( directoryFiles ),
```

This now works on `build`, `start`, and `watch` and will produce the same type of output as I posted before:
screenshot of the file directory and esbuild configuration file


I ran into an issue for a bit where I couldn't get this to run properly when I had multiple block source directories, but with this latest change I can build and watch everything including multiple blocks which will build into their own `/build/blocks/block-name/` directories.

**Comment by bplv112** [comment]
I've been running into some issues with the image min part which Corey mentioned here: https://github.com/WebDevStudios/wd_s/pull/751#issuecomment-934558170 
The fix that he added doesn't work for me I can't get the package from that commit. I'm currently looking a better solution to that.

**Pull request closed without merging**
