### PR TITLE
Feature/#363 add prettier

### LINKED ISSUE #363: Add Prettier
Add Prettier and config

https://prettier.io

### PR DESCRIPTION
**Pull request by jomurgel**
Closes #363

### DESCRIPTION ###
Add prettier.io as dev dependencies and added config file `.prettierrc`.

Reference: https://prettier.io/docs/en/configuration.html

The config (sans comments) was added as follows:

``` 
{
    "useTabs": true,         // Indent lines with tabs instead of spaces.
    "printWidth": 80,       // Specify the length of line that the printer will wrap on.
    "tabWidth": 4,            // Specify the number of spaces per indentation-level.
    "singleQuote": true,  // Use single quotes instead of double quotes.
    /**
     * Print trailing commas wherever possible.
     * Valid options:
     *   - "none" - no trailing commas
     *   - "es5" - trailing commas where valid in ES5 (objects, arrays, etc)
     *   - "all" - trailing commas wherever possible (function arguments)
     */
    "trailingComma": "all",
    /**
     * Do not print spaces between brackets.
     * If true, puts the > of a multi-line jsx element at the end of the last line instead of being
     * alone on the next line
     */
    "jsxBracketSameLine": false,
    /**
     * Specify which parse to use.
     * Valid options:
     *   - "flow"
     *   - "babylon"
     */
    "parser": "babylon",
    /**
     * Do not print semicolons, except at the beginning of lines which may need them.
     * Valid options:
     * - true - add a semicolon at the end of every line
     * - false - only add semicolons at the beginning of lines that may introduce ASI failures
     */
    "noSemi": false,
    /**
     * Add additional logging from prettierrc (not prettier itself).
     * Defaults to false
     * Valid options:
     * - true - enable additional logging
     * - false - disable additional logging
     */
    "rcVerbose": true
}
```

kapture 2018-04-10 at 12 19 53

### CODE REVIEW

**Review by gregrickaby — COMMENTED** [review]
@jomurgel Checked out your PR and it does work. I'm seeing changes (on save), however those changes, are throwing immediate ESLint errors. 😢 

I guess we didn't consider the fact that we'd need to make sure ESLint and Prettier rules are in sync?

kapture 2018-04-10 at 13 36 40

**Comment by jomurgel** [comment]
@gregrickaby The config should be inline with the .eslintrc.json.  It would also appear that your output is different than mine. 

I'll look to see what I can dig up. I wonder if the config file is not working for one of us.

I assume you ran `npm install` again and/or have the prettier VSCode extension installed?

**Comment by jomurgel** [comment]
Made several updates here to the configuration and `.eslintrc.js` file. The `.prettierrc` file has been removed and a couple of dependencies have been added to use the `.eslintrc.js` file to prettify. 

- Removes `.prettierrc` file.
- Adds `"eslint-config-prettier": "^2.9.0", "eslint-config-wordpress": "^2.0.0",  "eslint-plugin-prettier": "^2.6.0"` as devDepenencies. 
- extends `prettier` added to `.eslintrc.js`

You'll have to disable the global `.eslintrc.js` the file being pulled in from the WDS coding standards in order to test, but assuming everything is installed, we should see the appropriate behavior here.

Would love some testing to confirm.

**Comment by gregrickaby** [comment]
Confirmed working. I'm going to merge this in, and then start a discussion around making our linting config files a global thing either via Composer or NPM.

Thanks for your efforts @jomurgel!! 🌮

**Comment by jomurgel** [comment]
Alrighty, I've made some more changes here and confirmed this working in the following editors (with their settings).

I had to convert the `.eslintrs.js` to a `.eslintrc.json` file. The only issue might be that something doesn't match the js file, so might take a review on that.

Added support for React and JSX, Vue and Jest if we end up using that in our core theme ever, or end up using this as a global config file.

## `.eslintrc.json`
``` json
  "extends": [
    "wordpress",
    "plugin:react/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:jest/recommended",
    "plugin:vue/essential",
    "prettier"
  ],
```
and
``` json
"rules": {
    "prettier/prettier": "error",
}
```

## Sublime Text

**Requirements**
- https://packagecontrol.io/packages/JsPrettier
- https://github.com/xwartz/ESLint-Fix

**Configs**
Prevent prettier from formatting js files — use eslint.

JSPrettier User Config File
``` json
{
     "auto_format_on_save": true,
     "auto_format_on_save_excludes": [
     "*/node_modules/*",
     "*/*.js",
    ]
}
```

Keymap Users Config
``` json
{
    "keys": ["super+shift+h"],
    "command": "format_eslint"
}
```

screenshot 2018-04-18 09 15 33

## Atom

**Requirements**
- https://github.com/prettier/prettier-atom (atom will install other dependencies it might need)
- https://github.com/AtomLinter/linter-eslint

**Configs**
Prevent prettier from formatting js files — use eslint.

Eslint Settings (autoformat js files)
screenshot 2018-04-18 09 22 19

Prettier Settings (prevent prettier from formatting js files)
screenshot 2018-04-18 09 24 44

## VSCode

**Requirements**
- https://github.com/prettier/prettier-vscode

**Configs**
Prevent prettier from formatting js files — use eslint.
``` json
    "editor.formatOnSave": true,
    "[javascript]": {
        "editor.formatOnSave": false
    },
    "eslint.autoFixOnSave": true,
    "eslint.alwaysShowStatus": true,
    "javascript.format.enable": false,
```

## PHPStorm
I don't have PHPStorm, so need one of the other devs to test this out.

## Vim
Some have prettier working (incorrectly) with the prettier vim plugin.  I'm uncertain if https://github.com/prettier/vim-prettier/issues/42 would help at all getting it working with the repo's `eslintrc.json` config.

Per @phatsk who has this setup and working.
`~/bin/peslint`
```
#!/bin/bash
prettier --write $1
eslint --fix $1 --config=/Users/phatsk/src/WDS-Coding-Standards/WebDevStudios/.eslintrc.js --no-eslintrc
```
and then in my `.vimrc`
```
autocmd BufWritePost *.js,*.jsx !peslint <afile>
```

> for reference I had to remove `vim-prettier` and remove `eslint` as a Neomake linter (for those using Neomake)

## Notes
Also tested with Vue files, JSX/React, JS, SCSS, CSS, and JSON files and look 👍 

I did turn off my settings specifically for VSCode for testing to confirm. The settings above were still used.

## Caveats
- Running `prettier` directly won't work if we want to use our ESLint configs. This setup requires `eslint` to do the formatting for us as far as js is concerned. So, in our case `eslint --fix filename.js` would fix our js.
- Atom and VSCode have additional settings that could be used to make your life easier, but the configurations above seem to get everything working the same cross-editor.

**Comment by gregrickaby** [comment]
**VS Code: Confirmed** ✔️ 

I changed my user settings to match above and everything worked. I also used the workspace `settings.json` file (which override user settings, if you set this repo up as a Workspace) and code was reformatted too.

**Pull request closed without merging**
