### PR TITLE
Update .nvmrc to use version 16

### PR DESCRIPTION
**Pull request by bradp**
This seems to fix my issues from #688.

### CODE REVIEW

**Comment by bradp** [comment]
see also #690.

**Comment by gregrickaby** [comment]
@bradp @coreymcollins I'm going to push back on this one. There are reasons we support Node LTS (14) and not the latest stable (16)

1. LTS gives us breathing room for supporting Node for years vs. every six months.
2. Node 14 LTS adoption is still on the rise...many engineers are still on Node 12 and even 10. Requiring them to make the jump to 16 creates an even higher barrier to entry.

**Comment by bradp** [comment]
@gregrickaby are you able to successfully run an ‘npm run build’ with 14?

**Comment by gregrickaby** [comment]
@bradp Yes, after merging in https://github.com/WebDevStudios/wd_s/pull/690. I'm on Node `14.17.0` and NPM `7.16.0`

screenshot

**Pull request closed without merging**
