### PR TITLE
Restructure and ignore generated assets

### LINKED ISSUE #459: Do not track generated files
Keeping generated files in source control can sometimes create a mess and causes unnecessary merge conflicts that must be manually resolved.

It's been mentioned in the past that simply adding the generated files to `.gitignore` wouldn't be adequate as loading the theme for the first time would deactivate the theme and/or throw errors.

Here's what I'm proposing:
1. `style.css` should only contain the required masthead/metadata.
1. `assets/` should contain two directories: `src/` that contains all of the source JS/CSS/images/fonts and `dist/` that contains the generated assets.
1. Gulp should place generated files under `dist/`
1. The theme should load assets from `src/` when `WP_DEBUG` is set to `true`, load from `dist/` if not.
1. `assets/dist` should be added to `.gitignore`.

## Simplified directory structure
```
── assets
│   ├── dist
│   │   ├── css
│   │   ├── images
│   │   └── js
│   └── src
│       ├── images
│       ├── js
│       └── sass
└── style.css
```

### PR DESCRIPTION
**Pull request by aaroneaton**
Closes #459 

### DESCRIPTION ###
1. `style.css` contains only the required masthead/metadata.
1. `assets/` contains two directories: `src/` that contains all of the source JS/CSS/images/fonts and `dist/` that contains the generated assets.
1. Gulp/webpack should place generated files under `dist/`
1. The theme now loads un-minified assets from `dist/` when `SCRIPT_DEBUG` is set to `true`.
1. `assets/dist` has been added to `.gitignore`.

### SCREENSHOTS ###
screenshot

### OTHER ###
- [x] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [ ] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [x] Does this pass CBT?

### STEPS TO VERIFY ###
1. Pull down this branch
1. Run `npm install`
1. Add `define( SCRIPT_DEBUG, true );` to `wp-config.php`
1. Run `npm run dev` to build all of the files
1. Load the theme in the browser. All of the assets should load. You should not see any 404s.
1. Now remove the `SCRIPT_DEBUG` from `wp-config.php`
1. Run `npm run build`
1. Load the theme in the browser. All assets should load with `.min` as the filename suffix. You should not see any 404s.

### DOCUMENTATION ###
Will this pull request require updating the wd_s [wiki](https://github.com/WebDevStudios/wd_s/wiki)?
Yes. We'll need instructions on removing the `assets/dist` line in `.gitignore`.

### CODE REVIEW

**Review by efuller — COMMENTED** [review]
@aaroneaton I'm just creating notes here and hoping not to leave anything out with testing! After testing, we can tackle fixing up all the things 💥 

I followed the testing instruction up through number 5 and noticed a few things that we'll need to correct.

## 1
When I reloaded the homepage, I noticed that the `caret-down.svg` was throwing a 404.

That icon is being called here: https://github.com/WebDevStudios/wd_s/blob/feature/restructure-generated-assets/assets/src/sass/modules/navigation/_global-navigation.scss#L55

There are two reasons why it's throwing a `404`:
1. It resides in the `svg-icons` folder which doesn't get copied over which also makes sense. I think we will need to copy that icon into the `svg` folder. Also, as a team, we might want to clarify the distinction between the `svg` folder and the `svg-icons` folder. 
2. The `background` url will need to change to something like this: `background: url('../images/svg/caret-down.svg') no-repeat transparent;`. Again, this might be something we'll need to get the 👍 from everyone.

## 2
There are also a few issues around displaying `svg-icons`. Some of which I haven't been able to pinpoint.
1. The path here will need updating: https://github.com/WebDevStudios/wd_s/blob/feature/restructure-generated-assets/inc/scripts.php#L124
2. The path here will need updating as well: https://github.com/WebDevStudios/wd_s/blob/feature/restructure-generated-assets/inc/scripts.php#L124
3. I need to further test the `_s_display_svg()` function with a new, custom icon. I haven't been able to get it to work.

**Comment by efuller** [comment]
I've made some more tweaks to this PR and *I think* we are set.

### I made a couple of decisions:
1. Any SVG's that are used in Sass files will need to be added to the `images/svg` folder or else they will not be copied over to the dist folder.
2. Image URLs in Sass will need to be different than before so we can account for the new folder structure. The new format will look like this `background: url('../images/svg/caret-down.svg') no-repeat transparent;`

I searched all PHP/Sass files and worked to adjust file paths for images. Using the SVG PHP functions should now work correctly.

One additional testing item might be to see if these changes break anything when in `watch` mode.

I'd love to get some additional eyes on this before merging it into the Webpack/Gulp branch - /cc @gregrickaby @coreymcollins @jomurgel - or anyone else who wants to test!

**Comment by coreymcollins** [comment]
Testing this a bit today and noticing some things, plus want to note some other items below for clarification:

- In general `/svg-icons/` is used for single-color icons that will be used throughout the site, like a caret or arrow, while `/svg/` is for more dynamic SVG files like logos or anything that isn't a flat, single-color icon. 
- I'm not seeing anything happen with `npm run watch` running when I update the `customizer.js`, `scaffolding.js`, or `index.js` files in `assets/src/js`. If I update `index.js` to remove an import, nothing happens. If I then go save a file in the nested `/src/` directory, the files are compiled as expected. I would expect that if I update these top-level files, they would also generate the corresponding updated files.
- Every compiled non-min JS file in `/dist/js` has a bunch of webpack stuff at the top. Is this necessary in each of these files?

Going to break for lunch and then come back, but those are just some initial notes/findings so far (cc @aaroneaton @efuller)

**Comment by coreymcollins** [comment]
I think we could clean up some redundancies around the SVG pieces.

If I save a file in `/assets/src/images/svg-icons/`, then `/dist/images/svg-icons/` is updated.

If I save a file in `/assets/src/images/svg/`, nothing happens elsewhere. If I then run `npm run build`, the same file is duplicated in `/assets/src/images/svg`. Is there a reason to do this duplication? It seems odd to me to have two of the same files living in the theme in different locations. If nothing else, it will cause confusion as to why the same file exists twice.

My thoughts on the SVG portion:
- We don't need `/assets/dist/images/svg-icons/` at all since nothing ever goes into it
- We need to determine if we need `/assets/dist/images/svg/` at all and if there's a point in duplicating the same files that exist in `/assets/src/images/svg`
- If we do want to keep the practice of moving SVG images into the `/dist/` folder, I'd like to:
    1. See this happen on `npm run watch` the same way the `/svg-icons/` piece works
    2. Run a cleanup process after the file is moved to remove it from the `/src/` directory
- If we don't see a need for duplicating the files, we could simply save SVG images in `/assets/dist/images/svg/` and not worry about duplicating/moving them from `/src/`

**Comment by aaroneaton** [comment]
The idea for having svg directories in both `src/` and `dist/` allow us to always know where an image is pulled from depending on the environment. Devs also know that all new files should be created in `src/`. If we were to add files to `dist/` then they would be ignored. 

It does seem redundant if we are only copying the SVG files, but having that task allows us to add steps such as optimization/minification.

**Comment by coreymcollins** [comment]
Gotcha – that makes sense. Thanks, Aaron!

With that in mind, it would be great to see the SVG tasks run while `npm run watch` is going, so devs don't need to exit, run `npm run build`, and then kick up `npm run watch` again while actively working and adding SVGs.

**Comment by aaroneaton** [comment]
@coreymcollins Latest commit adds SVGs to watch.

**Comment by coreymcollins** [comment]
Thanks for that update! Adding new SVGs with `npm run watch` is now working which is great. I think there may need to be some cleanup functions run as well, though, as removed SVGs are still showing in my `/dist/` folder.



These were my steps:
1. Started `npm run watch`
2. Added `paper.svg` to `/src/images/svg/`. The image was copied over to the `/dist/` directory.
3. Removed `paper.svg` from `/src/images/svg/`. The file was not removed from the `/dist/` directory.

I thought maybe it would run the full process if I added another image so, I added `list-card.svg` to the `/src/` directory which was copied to `/dist/` as expected, but the old `paper.svg` still remained.

Adding SVGs to the `/svg-icons/` directory looks to be working as expected on both addition and removal of files from the `/src/` directory.

**Comment by aaroneaton** [comment]
@coreymcollins Got the image tasks updated so the dist directory is cleared out before processing. This should remove any images deleted in src.

**Comment by coreymcollins** [comment]
That looks to be working now!

I'd love to sit down and chat with you & Greg about this + #452 and a plan to get this all sewn up in a pretty lil package.

Goals are to:
- [ ] Establish a plan to merge all of the work in a single branch
- [ ] Test amongst the greater team so we have more folks kicking the wheels
- [ ] Set a rollout date
- [ ] Write documentation for both internal and external purposes
- [ ] Release!

**Pull request closed without merging**
