### PR TITLE
Feature/css js organization 6-14-2021 Update

### LINKED ISSUE #616: Idea: Simplification & organization of the SCSS
The SCSS should be organized so that it is easier to understand what each partial is styling. Additionally, it should be scoped better to not have global styles override block styling.

### LINKED ISSUE #621: Idea: `/components` folder should be renamed to `/js`
We have a folder named `/scss` but our JavaScript is named `/components` and it's confusing.

I'd like to propose the following:

```bash

js/
├─ components/
│  ├─ accordion.js
│  ├─ mobile-menu.js
│  ├─ modal.js
│  ├─ navigation-primary.js
│  ├─ etc...
├─ utility/
│  ├─ js-enabled.js
│  ├─ skip-link-focus.js
│  ├─ window-ready.js
│  ├─ etc...
```

Thoughts?

### PR DESCRIPTION
**Pull request by coreymcollins**
Closes #616 
Closes #621
Closes #638 

### DESCRIPTION
I'm going to copy the original description from @itsamoreh's initial PR below.

I created a new branch from his original feature branch and merged `main` in, then started working toward moving and consolidating some of the styles and scripts. I didn't want to get too handsy with his original PR branch, but there have been a lot of changes merged in lately and I wanted to try to get a jump on some of this work while also merging in the latest package updates, Github actions, and SVG updates.

Of note in this PR:
- Completely deleted the `accordion.js` file since we don't even use that in the theme anymore
- Removed a bunch of global stylesheets from the old way
- Moved some bits and pieces into the Tailwind config file (container styles, and some basic globals on things like `pre` tags, tables, lists, etc.)
- Replaced the old `/js/` and `/scss/` directories with the new structure

I haven't looked into the typography package mentioned in the original PR yet, just trying to get a base going with everything

-----

### From Amor

This is my proposal for #616.

#### Currently, it's hard to understand how JS, SCSS, and PHP files relate to each other.
* For example, the mobile off-canvas navigation's markup is in `template-tags.php`, called by a function `_s_display_mobile_menu()` but it's styles and js are located in two separate files - `scss/modules/_mobile-menus.scss`, `components/mobile-menu.js`, `scss/modules/_off-canvas.scss` and `components/off-canvas.js`.
* If I needed to make changes to the mobile off canvas nav, I have to track down four different files.
* There are currently no sub directories in JS `components/` which leads to unorganized JS source files.

#### There is no longer a need for unscoped `base` styles now that we use Tailwind.
* Unscoped base styles go against the point of Tailwind. When building blocks, we should not have to worry about overriding existing styles. Here's a link to Tailwind docs talking about [why headings have no style by default](https://tailwindcss.com/docs/preflight#headings-are-unstyled).
* Instead of base styles, we should use [tailwindlabs / tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography) to style user generated content from WYSIWYG fields and style Gutenberg text blocks with scoped block specific stylesheets (see `src/scss/blocks/core/`).

### Why not atomic design?
* Atomic design is great for a JS framework component based system but there are two reasons I don't think it will work in wd_s.
  * Confusion created by WordPress nomenclature like template tags, blocks, templates.
    * `template tag == atomic molecule || atomic atom || atomic organism`, `gutenberg block == atomic atom || atomic molecule || atomic organism` and `template == atomic template || atomic page`. There is too much room for interpretation IMO and this might cause confusion.

### Proposal
I'm proposing the following structure. This structure makes it really easy to see how the different theme files relate to each other because they all follow the same naming convention.
```
sass/
├─ blocks/
│  ├─ core/
|  |  ├─ _heading.scss
|  |  ├─ _paragraph.scss
|  |  ├─ index.scss
│  ├─ acf/
|  |  ├─ _example-block.scss
|  |  ├─ index.scss
│  ├─ index.scss
├─ template-tags/
│  ├─ _accordion.scss
│  ├─ _button.scss
│  ├─ _card.scss
├─ templates/
│  ├─ _header.scss
│  ├─ _single.scss
```
```
js/
├─ blocks/
│  ├─ acf/
|  |  ├─ example-block.js
|  |  ├─ index.js
│  ├─ index.js
├─ global/
│  ├─ index.js
│  ├─ js-enabled.js
│  ├─ window-ready.js
├─ template-tags/
│  ├─ accordion.js
│  ├─ index.js
├─ templates/
│  ├─ single.js
│  ├─ index.js
```

### SCREENSHOTS

If we go in this direction, here's what VSCode's Command + P menu would look like for different things. 

A custom ACF gutenberg block called Testimonials:
2021-04-22 at 13 42 51

Shared CPT single as well as a custom CPT single template for Recipes:
2021-04-22 at 13 37 32

### OTHER

- [x] Is this issue accessible? (Section 508/WCAG 2.0AA) N/A
- [x] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [x] Does this pass CBT? N/A

### STEPS TO VERIFY

Coming soon...

### DOCUMENTATION

Coming soon...

### CODE REVIEW

**Comment by coreymcollins** [comment]
I think this might actually be ready for a review. @itsamoreh, I'm specifically interested in your feedback on some of the structure and if your vision includes breaking things up any further.

I would suggest we focus on just the reorganization of the assets for this PR, and if you wanted to spin up an issue for the typography suggestion we could look at that separately as its own thing.

So far, I've moved the assets per the suggestions above and reworked some of our config files where needed. Everything is building and compiling as expected!

Screenshot below of the `cmd + p` usage in VS Code looking for the modal:
modal VS code search

**Comment by itsamoreh** [comment]
@coreymcollins I really like all of this! My only suggestion would be to rename the `scss/base` to `scss/global` to match the "global" naming convention in `js/global` and `scss/wordpress-global` (as I'm typing this out, maybe get rid of the "s" on `wordpress-globals`?

Other than that this looks awesome! Thank you for moving this along.

**Comment by coreymcollins** [comment]
Ah, that's a good catch – I'll tweak that. Thanks!

**Comment by coreymcollins** [comment]
I think this might be ready for a full review.

I've gone through and removed all `@TODO` messages in the partials and updated styles where needed. Most of the things the `@TODO` messages were calling out were things already taken care of by global styles (for example, out of the box the sidebar options in the Gutenberg editor for blocks is working and applying styles as expected).

I added the [Block Unit Test plugin](https://wordpress.org/plugins/block-unit-test/) to test all of the blocks on one page to make sure styles were doing what they should, that captions were working as expected, etc.

Would love to get eyes and hands on this sucker to see if we can bring in these updates – thanks, y'all!

**Review by gregrickaby — APPROVED** [review]
@coreymcollins I'm able to successfully spin up a local, change SCSS and JS and everything is compiling. 👍🏻 

I'll let @itsamoreh and other FEEs chime in on the other stuff.

**Pull request merged**
