### PR TITLE
Set border radius variable, for easy consistency

### PR DESCRIPTION
**Pull request by pmgarman**

### CODE REVIEW

**Comment by colorful-tones** [comment]
I like this idea, but would like to see the variable moved into a new, separated partial as _grid-settings.scss does not make sense to me and I would not look there for it. Maybe a new _box-model.scss partial in /variables/?

**Comment by pmgarman** [comment]
Yeah I wasn't sure where it best fit and wasn't sure if it made sense to add a file JUST for one variable. Granted, its sass so it gets compiled anyways...

**Comment by colorful-tones** [comment]
I vote for a new partial. I think _grid-settings.scss could be refactored as well, as it is specific to Bourbon Neat. 

I'm actually a proponent of having one large variables file (as opposed to several separate) so I can see it all in one place, but that is a whole other ballgame :-)

**Comment by pmgarman** [comment]
@colorful-tones i updated the PR with the additional partial, because you are right it should be separated.

**Pull request merged**
