### PR TITLE
Theme/#415 remove google+

### LINKED ISSUE #415: Remove Google+ From Social Functions
Since Google+ is being shut we should remove any instances of Google Plus from our social functions, icon svgs, etc.

Example: https://github.com/WebDevStudios/wd_s/blob/master/inc/template-tags.php#L364

### PR DESCRIPTION
**Pull request by mharis**
Closes #415 

### DESCRIPTION ###

Removes Google+

- Removed styling for Google+.
- Removed Google+ from functions.

### SCREENSHOTS ###

screenshot 2018-10-24 00 32 47

### OTHER ###
- [X] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [X] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [X] Does this pass CBT?

### STEPS TO VERIFY ###
Verify the code instances were removed in this PR.

### DOCUMENTATION ###
👎 Nope

### CODE REVIEW

**Review by coreymcollins — CHANGES_REQUESTED** [review]
This is looking pretty good! I checked out the customizer and tested the output of social icons and no longer see a reference to Google+. Byyyyeeeeeee :wave:

Could you update the `/assets/images/svg-icons/_IcoMoon.json` file to remove its references to the Google+ icon? There are instructions in the `README` file in the same directory on how to manage the IcoMoon file.

Before merging in, could you also update this piece in the wiki to remove the reference to Google+?
https://github.com/WebDevStudios/wd_s/wiki/Template-Tags#display-social-links-via-customizer

**Comment by coreymcollins** [comment]
Found another Google+ reference in the wiki which will need to be removed: https://github.com/WebDevStudios/wd_s/wiki/Customizer#social-links

Thanks!

**Comment by mharis** [comment]
All done @coreymcollins !

The format of selection js file is a bit different now but we're good to go.

**Comment by coreymcollins** [comment]
This is looking good! I imported the updated IcoMoon file into IcoMoon and got all of the expected icons.

Wiki updates are also looking good. Going to merge this in!

**Review by coreymcollins — APPROVED** [review]

**Pull request merged**
