### PR TITLE
Feature/#770 posted on tweaks

### LINKED ISSUE #770: The "posted_on" function is obtuse and not functional unless rewritten
This is a staple of pretty much every site; all blog posts either display the author (byline), the date/time posted, or both. The current function _works_ but isn't intuitive at all.

Further, you can't use it to display either/or the date or author; you simply get the entire string as written.

Preferably, this would accept some parameters to allow display of the date and byline separately.

### PR DESCRIPTION
**Pull request by batesweb**
Closes #770 

### DESCRIPTION

Refactors the `_s_posted_on()` function to make the code more readable and configurable. This function has been replaced by two new functions: `_s_post_date()` and `_s_post_author()`.

### OTHER

- [x] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [x] Does this pass CBT?

### STEPS TO VERIFY

View singles/archives to make sure post dates and authors are being rendered correctly.

### DOCUMENTATION

Will this pull request require updating the wd_s [wiki](https://github.com/WebDevStudios/wd_s/wiki)?

### CODE REVIEW

**Review by oliverharrison — COMMENTED** [review]
This looks good to me. A nice improvement and much more readable than the previous function.

**Comment by coreymcollins** [comment]
@batesweb – this will require some updates to the wiki (https://github.com/WebDevStudios/wd_s/wiki/Template-Tags#post-meta-information). Could you prep that for when this is ready to merge in? Thanks!

**Review by coreymcollins — APPROVED** [review]

**Comment by batesweb** [comment]
Here's the updated documentation. This will replace the "Post Meta Information" section:

## Post Date
`_s_post_date`

Prints HTML with the post date for the current post.

**Usage:** `<?php _s_post_date(); ?>`

**Output:**
``` html
<time class="entry-date published" datetime="2021-10-12T16:27:10+00:00">October 12, 2021</time>
```
**Location:** `/inc/template-tags.php`

## Post Author
`_s_post_author`

Prints HTML with the post author for the current post.

**Usage:** `<?php _s_post_author(); ?>`

**Output:**
``` html
<span class="post-author">
     by <span class="author vcard">
	<a class="url fn n" href="http://wds-dev.local/author/admin/">admin</a>
     </span>
</span>
```
**Location:** `/inc/template-tags.php`

**Comment by coreymcollins** [comment]
This is looking really great! I've tested the split functions and passed in my own strings to make sure those work.

One thing I've noticed is that while we have a `content-search.php` file, this is never used because there's no `search.php` file in the top-level theme. The changes made to `content-search.php` are never seen currently because the search results page uses `content.php`.

Would you be able to add a top-level `search.php` file and make any necessary tweaks to `content-search.php` to make sure search results are displayed nicely, and that the date/author functions are working as expected?

Thanks!

**Comment by batesweb** [comment]
I can definitely set that up, @coreymcollins , but should that be a part of this PR? @oliverharrison and I had talked about adding in some of those "missing" files (search.php, page.php, etc.), but it seems like that should be its own PR.

**Comment by coreymcollins** [comment]
I feel like it's a small enough addition that it could be added here, especially if we're trying to leverage the new functions in the `content-search.php` file. Without a `search.php` file (or a conditional elsewhere) calling for that `content-search.php` file, it could be confusing to a new user as to why their changes aren't showing up if they edit the template part.

**Comment by batesweb** [comment]
@coreymcollins is that what you had in mind?

**Comment by coreymcollins** [comment]
This is great – thanks! I'll merge this in and add your updates to the docs.

**Review by coreymcollins — APPROVED** [review]

**Pull request merged**
