### PR TITLE
Update functions.php to only include files from inc folder

### PR DESCRIPTION
**Pull request by bradp**
### DESCRIPTION

Updated `functions.php` to only handle including files from the `inc/` folder. Moved the setup functions to a separate `inc/setup.php`.

### OTHER

- [x] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [x] Does this pass CBT?

### STEPS TO VERIFY

Activate theme as normal, nothing should change.

### CODE REVIEW

**Comment by gregrickaby** [comment]
I'd like @coreymcollins and others to weigh in on this PR. Chalk this up to _this is how our `functions.php` has always worked_ and I want to be sure everyone is good with the change.

**Comment by coreymcollins** [comment]
Yeah, I think I'm not opposed to this in theory or anything but probably a good one to just run by the team (maybe on the FEE scrum or monthly engineering call?) before making any merges so nobody is surprised by it.

**Comment by bradp** [comment]
I also kind of like having each include being it's own line with a fancy file, so if we want to do a happy medium and just break setup into it's own file I'm happy to modify the PR to do that only if we want

**Review by gregrickaby — APPROVED** [review]

**Comment by bradp** [comment]
☎️  brrrrrrring merge conflict call for @bradp

**Comment by bradp** [comment]
Before merge, one last question for @gregrickaby @coreymcollins related to my [comments above](https://github.com/WebDevStudios/wd_s/pull/676#issuecomment-862524932).

Do we prefer including all these like how the PR has it now in just an array or do we want to keep the more commented style?

```php
return [
	'inc/setup.php', // Theme set up. Should be included first.
	'inc/compat.php', // Backwards Compatibility.
	'inc/customizer/customizer.php', // Customizer additions.
```

vs

```php
/** * Load styles and scripts. */
require get_template_directory() . '/inc/scripts.php';

/** * Load custom filters and hooks. */
require get_template_directory() . '/inc/hooks.php';
```

**Comment by coreymcollins** [comment]
I like the slimmed down version myself. I mentioned this ticket to the FEEs yesterday on the FEE Scrum and some have popped in to give 👍🏻 on the ticket; I talked through this update and nobody had any objections or concerns.

**Comment by bradp** [comment]
wait hold on how did I mess this up resolving the merge conflicts wtf

**Comment by bradp** [comment]
Okay - fixed those merge conflicts sheeeeeesh

**Review by coreymcollins — APPROVED** [review]

**Pull request merged**
