### PR TITLE
Breakpoints to variables

### PR DESCRIPTION
**Pull request by rcstr**
makes easier autocomplete on ide's and avoids typing mistakes

### CODE REVIEW

**Comment by aubreypwd** [comment]
I've always had an easy time with autocomplete, are you saying in your IDE you can use `$bp` in one file  and it finds the variable in this file?

**Comment by rcstr** [comment]
@aubreypwd  at least on Atom and Jetbrains IDE's autocomplete works with variables, ST also autocomplete strings so this shouldn't be a problem on ST.

**Comment by coreymcollins** [comment]
Autocomplete only works for me when I've already used the variable in the partial.  So if I'm going to use wider-than( tablet ), "tablet" doesn't autocomplete unless I've already typed it in the same partial.

I would suggest not using $bp-variable-name because BP makes me think of BuddyPress which this is not.

**Comment by rcstr** [comment]
@coreymcollins i'm agree on that, i used bp because of breakpoints.
but i'm open to ideas

**Comment by coreymcollins** [comment]
@rommelxcastro I definitely get that, just want to make sure we don't tread into murky waters sharing prefixes with other entities.  That being said, I don't have any better ideas at the moment and am just causing problems :D

**Comment by aubreypwd** [comment]
Maybe `$bpoint-tablet-landscape`, `$break-tablet-landscape`, or the obvious `$breakpoint-tablet-landscape`? I'm more inclined to go with the obvious one.

**Comment by coreymcollins** [comment]
Yeah, why not just use the full word and then everyone will always know what those variables mean.  Just be as obvious with it as possible without abbreviations.  +1 @aubreypwd

**Comment by aubreypwd** [comment]
I'm still wondering what the benefit of this is as having it be a variable in `breakpoints.scss` doesn't cause it to autocomplete in other file when I type `$breakpoint-` in Sublime?

**Comment by gregrickaby** [comment]
We now have breakpoints as variables! 

See: https://github.com/WebDevStudios/wd_s/blob/master/sass/utilities/variables/_breakpoints.scss

Associated issue: https://github.com/WebDevStudios/wd_s/issues/121

**Pull request closed without merging**
