### PR TITLE
Lets own it

### PR DESCRIPTION
**Pull request by blobaugh**
I really dislike seeing "Automattic" on all our builds. Since we have hacked _s enough that it is wd_s lets own it and show ourselves :)

### CODE REVIEW

**Comment by Mamaduka** [comment]
Nooice!

**Comment by jazzsequence** [comment]
:100:

**Comment by gregrickaby** [comment]
I'm not trying to be Debby Downer, but we try to remain current with Underscores' markup. Swapping out text-domains and other markup makes it difficult to merge upstream. 

I completely understand the motivation behind this PR - and am excited about branding WDS, but none of this matters since it's wiped out on a new project. Furthermore, I don't remember the last time we ever put our name in the footer of a client site.

I suppose a case could be made for branding because this theme could be used by other individuals (or agencies), however, in the entire history of this fork - only one (maybe two) pull requests have come from non-WDS employees. 

Which leads me to believe: _at the end of the day, this is an internal WDS tool. Because of this, I'd like to make maintaining upstream compatibility, and keeping merge conflicts to a minimum, one of our priorities._

**Comment by dremeda** [comment]
If we're going to add branding, I would recommend we still note the original source which is _s & Automattic.

"Proudly powered by wd_s based on _s.  

Or something to that nature. 

It may be different, but this is still a derivative work using _s source. I can see a time where it's disassociated completely from _s and Automattic, can we really say we're there?

Dre

**Comment by coreymcollins** [comment]
I agree with Greg and Dre on this one.  I don't feel the need to disassociate with _s or Automattic; we're clearly forking their theme and making it work for our own needs.  In the open-source and community-based climate that is WordPress, why would we want to remove the acknowledgement of where we started from with this theme?

**Comment by bradp** [comment]
Echoing the agreement above, let's own it, but let's also give credit where credit is due.

**Comment by bradp** [comment]
Also, as the one who did the last upstream merge from _s, I will strongly agree with Greg, the further we get away from _s, the harder upstream merges will become, if we want to continue those.

**Comment by gregrickaby** [comment]
Underscores development mirrors Core. When template tags and other functionality are moved to/from Core, it also happens in _s. I think what makes _s such an attractive theme (other than it being bare bones), is it really is an "officially sanctioned" theme from the mother ship. 

If we're really ready to "own it" and break away from _s, are we prepared to take on the responsibility of maintaining an entire theme? 

Right now, we maintain the Sass and merge in theme/markup changes upstream from _s...which makes it easy to stay current with Core. Not to mention the hundred or so contributors to _s constantly making improvements. We get all the benefits of having an amazing theme, while only maintaining 50% of it.

Again, I'm not being Debby Downer, but, is WDS really ready to make this theme our own?

**Comment by stacyk** [comment]
I use this repo all the time on new projects :)

**Comment by blobaugh** [comment]
There have been several instances where clients viewed a dev site and asked about the "Automattic" in the footer. Being that this is used by not Automattic it does not seem right to put that out to clients. If we do not merge this as is could we get a setup script going that either replaces or strips out the text at least? That should still allow easy upstream merges.

**Comment by dremeda** [comment]
That's a different issue I think. The public facing fork should attribute Automattic in my opinion. I don't have any gripes about removing Automattic on our dev servers if it can be done in a way isolated to the client build and doesn't affect the fork.

**Comment by gregrickaby** [comment]
The solution to this problem is: the person scaffolding the client site, needs to remove the attribution. We could also add this to our (beta) theme generator: https://github.com/WebDevStudios/wd_s/issues/64

**Comment by coreymcollins** [comment]
If we're having an issue where clients are seeing something attributed to Automattic, that's a WDS issue and not an issue with the _s/wd_s themselves.  We should be on the ball and making all of that stuff the first things we update/remove/change when pushing to a new repo.

**Comment by bradp** [comment]
Why not remove the footer attribution altogether and make sure we make the attribution known in the header/functions.php/README,etc?

**Comment by jazzsequence** [comment]
+1 to @gregrickaby's [comment](https://github.com/WebDevStudios/wd_s/pull/83#issuecomment-144123860). We can address it in the generator. That way core _s stays the same and our customizations are still automated. :boom:

**Comment by blobaugh** [comment]
I am fine with that @bradp, but it seems that the upstream merge becomes the issue.

@dremeda No matter what it shows on Github that this is an _s fork.

@coreymcollins correct. This PR started as a way to resolve that issue.

@gregrickaby Putting it in the script is a great compromise for ease of upstream merging and properly setting things up for clients.

**Comment by gregrickaby** [comment]
As mentioned on A-Team's scrum, we're going to leave this as-is for the public facing repo. 

When we scaffold the theme using https://github.com/WebDevStudios/wd_s/issues/64, this will handle the removal of the footer markup (entirely - since we don't use it) based on a _"Do you want to include the attribute?"_ question in the generator. Folks can choose Yes, and the attribute will remain.

The generator will also change the Author in style.scss as well: https://github.com/WebDevStudios/wd_s/blob/master/sass/style.scss#L4

Thanks for a great discussion! Love the democracy!

**Pull request closed without merging**
