### PR TITLE
Feature/site editor index

### PR DESCRIPTION
**Pull request by khleomix**
# Closes
- #1093
- #1092
- #1091
- #1089
- #1088
- #1086
- #1085
- #1084 
- #1083
- #1082 
- #1081 
- #1080 
- #1077
- #1076
- #1075
- #1074
- #1073

## What type of PR is this? (put an x to all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [x] 🤖 Build
- [x] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Link to test
Test locally

## Description
- Fix site editor issues with blank page
- Fix themejson styles
- Fix logged Github issues referenced above
- Updated dependencies logged by dependabot

## Mobile & Desktop Screenshots/Recordings

Site-Title-–-Just-another-WordPress-site

Page-not-found-–-Site-Title

Hello-world-–-Site-Title

Site-Title-–-Just-another-WordPress-site (1)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [Confluence](https://webdevstudios.atlassian.net/wiki/spaces/wds1/pages/2988474566/Feature+Documentation)
- [x] 🙅 no documentation needed

## Others

- [x] 🦮 Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] 🙌 Does this issue pass all the linting? (PHPCS, ESLint, SassLint)

### CODE REVIEW

**Review by martinDolan — APPROVED** [review]
Thanks JC!

**Comment by lepittenger** [comment]
I'm still seeing the pagination links off to the side 
Screenshot 2023-09-29 at 2 59 45 PM

**Review by aslamatwebdevstudios — COMMENTED** [review]
In the file at the line below, wrap it with `<div class="is-layout-constrained">` to align pagination with content area.
https://github.com/WebDevStudios/wd_s/blob/2cc09c073bb9a4bea3cce4c29a1a855afd8b706e/inc/template-tags/print-numeric-pagination.php#L43

**Review by aslamatwebdevstudios — APPROVED** [review]
All good 👍

**Review by lepittenger — APPROVED** [review]
Looks good!

**Pull request merged**
