### PR TITLE
Feature/#747 Scafffolding Template

### LINKED ISSUE #747: Scaffolding Template fix
The scaffolding template is currently not working the way it's supposed to work.

Things to do:
- Update accordion markup.
- Add tailwind classes to work with the scaffolding template.

Scaffolding-–-Site-Title

### PR DESCRIPTION
**Pull request by khleomix**
Closes #747 

### DESCRIPTION

- Add a CSS accordion to replace the broken one.
- Add tailwind classes to work with the scaffolding template.
- Make it easier to copy/paste theme color name/hex code
- Add in-page menu
- Add full width style using the `alignfull` class

### SCREENSHOTS

Scaffolding-–-Site-Title

Scaffolding-–-Site-Title (1)

Screen Recording 2021-12-06 at 10 04 25 PM

### OTHER

- [x] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] Does this issue pass all the linting? (PHPCS, ESLint, SassLint)
- [x] Does this pass CBT?

### STEPS TO VERIFY

How do we test this?

### DOCUMENTATION

Will this pull request require updating the wd_s [wiki](https://github.com/WebDevStudios/wd_s/wiki)?

### CODE REVIEW

**Comment by coreymcollins** [comment]
This in-page sticky menu is the best! Starting to review now, will probably kick the wheels some more tomorrow and merge in if all looks good.

Thanks, JC!

**Comment by coreymcollins** [comment]
I think overall this is looking great, but I do have one accessibility suggestion.

If I'm tabbing through this page, I can't tell when I'm focused on the accordion items. Could we do something like this `.scaffolding-document.tabs .tab-toggle:focus + .tab-label` to target the labels and change their background color if the input is focused? That worked for me in dev tools but maybe there's a way to do it with less specificity.

Here's what it looks like tabbing through with a very obnoxious orange set as the focus state:

https://user-images.githubusercontent.com/954724/146575301-e0409dfe-3ea4-4929-9c45-8fb4e9673ecf.mov

**Comment by khleomix** [comment]
@coreymcollins Over to you again :) I've added the WDS orange for both `:checked` and `:focus`. Also updated branch with `main`

Scaffolding-–-Site-Title

**Comment by coreymcollins** [comment]
This is looking good visually but I am having some usability issues on the frontend:
- When I tab onto the accordion trigger, the accordion opens automatically
- I have a real hard time closing the accordion. I can sometimes get it to close by clicking but often the only time I can get it to close is to click outside of it.

Screen recording attached.

https://user-images.githubusercontent.com/954724/161281975-005fadf0-a96e-40db-8649-04c217b4ad98.mov

**Comment by coreymcollins** [comment]
Just pushed up an adjustment for this:
- Tab headings will highlight orange on tab focus
- You can hit space to expand or contract the accordion
- Clicking/tapping still continues to work as expected to work the accordion

Screen recording:

https://user-images.githubusercontent.com/954724/169083820-8db1711f-aedd-43aa-9ace-434b080cbfb4.mov

**Review by oliverharrison — APPROVED** [review]
This adds some great functionality. Nice work @khleomix and @coreymcollins!

**Pull request merged**
